# Generated by Django 5.2.8 on 2026-01-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='street_name',
        ),
    ]
