"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see

https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from shutil import which
from django.templatetags.static import static
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load prod env file
load_dotenv(
    os.path.join(BASE_DIR, '.env')
)

# Application definition

INSTALLED_APPS = [
    # Custom admin UI
    'unfold',
    'unfold.contrib.forms',

    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    # Tailwind
    'tailwind',
    'theme',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.sites',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    "drf_yasg",
    "django_filters",

    # Local apps
    'auth_service',
    'map_service',
    'ml_service',
    'leaderboard_service',
    'report_service',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR / 'media/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static/'),
    os.path.join(BASE_DIR / 'theme/static/'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tailwind settings
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = which('npm')
INTERNAL_IPS = [
    '127.0.0.1',
]

# Unfold settings
UNFOLD = {
    'SITE_TITLE': "TrashTrails Secret Dashboard",
    'SITE_HEADER': 'Control Center of Chaos',
    'SITE_SUBHEADER': 'Dashboard of Dubious Decisions',
    'SITE_ICON': lambda request: static("common/images/logomark/cyan.svg"),
    'SITE_FAVICONS': [
        {
            'rel': 'icon',
            'sizes': '32x32',
            'type': 'image/svg+xml',
            'href': lambda request: static('common/images/logomark/cyan.svg')
        },
    ],
    'THEME': 'light',
    'BORDER_RADIUS': "8px",
    'SIDEBAR': {
        'navigation': [
            {
                "title": "Auth Service",
                "items": [
                    {
                        "title": "User Profiles",
                        "link": "/admin/auth_service/userprofile/",
                        "icon": "account_circle",
                    },
                ],
            },
            {
                "title": "Auth Tokens",
                "items": [
                    {
                        "title": "Auth Tokens",
                        "link": "/admin/auth_service/authtoken/",
                        "icon": "token",
                    },
                ],
            },
            {
                "title": "Authentication and Authorization",
                "items": [
                    {
                        "title": "Users",
                        "link": "/admin/auth/user/",
                        "icon": "person",
                    },
                    {
                        "title": "Groups",
                        "link": "/admin/auth/group/",
                        "icon": "groups",
                    },
                ],
            },
            {
                "title": "Leaderboard",
                "items": [
                    {
                        "title": "Category Point Multipliers",
                        "link": "/admin/leaderboard_service/categorypointmultiplier/",
                        "icon": "category",
                    },
                    {
                        "title": "Endorsements",
                        "link": "/admin/leaderboard_service/endorsement/",
                        "icon": "front_hand",
                    },
                    {
                        "title": "Point Configurations",
                        "link": "/admin/leaderboard_service/pointconfiguration/",
                        "icon": "tune",
                    },
                    {
                        "title": "Score Rules",
                        "link": "/admin/leaderboard_service/scorerule/",
                        "icon": "rule",
                    },
                    {
                        "title": "Score Transactions",
                        "link": "/admin/leaderboard_service/scoretransaction/",
                        "icon": "swap_horiz",
                    },
                    {
                        "title": "Severity Point Values",
                        "link": "/admin/leaderboard_service/severitypointvalue/",
                        "icon": "priority_high",
                    },
                    {
                        "title": "User Scores",
                        "link": "/admin/leaderboard_service/userscore/",
                        "icon": "leaderboard",
                    },
                ],
            },
            {
                "title": "Map Service",
                "items": [
                    {
                        "title": "Locations",
                        "link": "/admin/map_service/location/",
                        "icon": "personal_places",
                    },
                ],
            },
            {
                "title": "Report Service",
                "items": [
                    {
                        "title": "Report Severities",
                        "link": "/admin/report_service/reportseverity/",
                        "icon": "android_cell_4_bar",
                    },
                    {
                        "title": "Report Images",
                        "link": "/admin/report_service/reportimage/",
                        "icon": "art_track",
                    },
                    {
                        "title": "Reports",
                        "link": "/admin/report_service/report/",
                        "icon": "receipt_long",
                    },
                    {
                        "title": "Trash Categories",
                        "link": "/admin/report_service/trashcategory/",
                        "icon": "delete_sweep",
                    },
                ],
            },
            {
                "title": "Sites",
                "items": [
                    {
                        "title": "Sites",
                        "link": "/admin/sites/site/",
                        "icon": "language",
                    },
                ],
            },
            {
                "title": "Token Blacklist",
                "items": [
                    {
                        "title": "Blacklisted Tokens",
                        "link": "/admin/token_blacklist/blacklistedtoken/",
                        "icon": "block",
                    },
                    {
                        "title": "Outstanding Tokens",
                        "link": "/admin/token_blacklist/outstandingtoken/",
                        "icon": "vpn_key",
                    },
                ],
            }
        ]
    },
    'COLORS': {
        'base': {
            50: '246,246,246',
            100: '231,231,231',
            200: '209,209,209',
            300: '176,176,176',
            400: '136,136,136',
            500: '109,109,109',
            600: '93,93,93',
            700: '79,79,79',
            800: '69,69,69',
            900: '61,61,61',
            950: '43,43,43',
        },
        'primary': {
            50: '235,241,255',
            100: '219,228,255',
            200: '190,204,255',
            300: '151,170,255',
            400: '110,123,255',
            500: '77,79,255',
            600: '47,32,254',
            700: '47,32,254',
            800: '41,30,181',
            900: '38,33,142',
            950: '24,19,83',
        }
    },
    'STYLES': [
        lambda request: static("unfold/fonts/inter/styles.css"),
        lambda request: static("unfold/fonts/material-symbols/styles.css"),
    ]
}

SITE_ID = 1

# REST configs
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        "rest_framework.authentication.SessionAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
