# Generated by Django 5.2.8 on 2026-01-13 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_service', '0004_reportseverity_trashcategory_alter_report_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('TITLE', 'Proper Title'), ('SEVERITY', 'Severity Level'), ('CATEGORY_RARE', 'Rare Category'), ('CATEGORY_COMMON', 'Common Category'), ('CATEGORY_GENERIC', 'Generic Category'), ('OBSERVATION_MIN', 'Observation Minimum'), ('OBSERVATION_PER_CHAR', 'Observation Per Character'), ('OBSERVATION_DEFAULT', 'Observation Default'), ('LOCATION', 'Location Filled'), ('IMAGE_FIRST', 'First Image'), ('IMAGE_ADDITIONAL', 'Additional Image'), ('IMAGE_MAX_COUNT', 'Max Images Count for Points')], max_length=50, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point Configuration',
                'verbose_name_plural': 'Point Configurations',
            },
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, unique=True)),
                ('points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Score Rule',
                'verbose_name_plural': 'Score Rules',
            },
        ),
        migrations.CreateModel(
            name='CategoryPointMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Point multiplier for this category (e.g., 1.5 = 50% more points)', max_digits=4)),
                ('rarity_level', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('VERY_RARE', 'Very Rare')], default='COMMON', max_length=20)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_multiplier', to='report_service.trashcategory')),
            ],
            options={
                'verbose_name': 'Category Point Multiplier',
                'verbose_name_plural': 'Category Point Multipliers',
            },
        ),
        migrations.CreateModel(
            name='ScoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REPORT_CREATED', 'Report Created'), ('REPORT_VERIFIED', 'Report Verified'), ('REPORT_CLEANED', 'Report Cleaned'), ('ENDORSEMENT_RECEIVED', 'Endorsement Received'), ('ENDORSEMENT_GIVEN', 'Endorsement Given'), ('BONUS', 'Bonus Points'), ('PENALTY', 'Penalty')], max_length=30)),
                ('points', models.IntegerField()),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of how points were calculated')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_transactions', to='report_service.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score Transaction',
                'verbose_name_plural': 'Score Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeverityPointValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=10)),
                ('severity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_value', to='report_service.reportseverity')),
            ],
            options={
                'verbose_name': 'Severity Point Value',
                'verbose_name_plural': 'Severity Point Values',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('monthly_points', models.IntegerField(default=0)),
                ('yearly_points', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('verified_reports', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('weekly_reset_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_reset_at', models.DateTimeField(blank=True, null=True)),
                ('yearly_reset_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score',
                'verbose_name_plural': 'User Scores',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='report_service.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'unique_together': {('user', 'report')},
            },
        ),
    ]
