# Generated by Django 5.2.8 on 2026-01-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
