# Generated by Django 5.2.8 on 2026-01-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0002_report_slug_report_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='street_name',
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
