# Generated by Django 5.2.8 on 2026-01-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0003_remove_report_street_name_alter_report_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Report Severities',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TrashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Trash Categories',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CLEANED', 'Cleaned')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='report_service.reportseverity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='report_service.trashcategory'),
            preserve_default=False,
        ),
    ]
