# Generated by Django 5.2.8 on 2026-01-10 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recyclable_detected', models.BooleanField()),
                ('materials', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_service.report')),
            ],
        ),
    ]
